import type { Skill, InstructorProfile, Booking, Review, Slot, AdminStats, User } from '../types'

export const mockSkills: Skill[] = [
  { id: 's1', name: 'Painting', slug: 'painting', description: 'Acrylic, watercolor and oil painting techniques for all levels.' },
  { id: 's2', name: 'Mehendi', slug: 'mehendi', description: 'Traditional and contemporary henna art for beginners to advanced.' },
  { id: 's3', name: 'Calligraphy', slug: 'calligraphy', description: 'Beautiful hand-lettering and script writing styles.' },
  { id: 's4', name: 'Resin Art', slug: 'resin-art', description: 'Create stunning jewelry, coasters, and artwork with epoxy resin.' },
  { id: 's5', name: 'Clay Modelling', slug: 'clay-modelling', description: 'Sculpt and hand-build with air-dry and polymer clay.' },
  { id: 's6', name: 'Handmade Crafts', slug: 'handmade-crafts', description: 'Macrame, weaving, fabric art, and more handcrafted creations.' },
]

export const mockUser: User = {
  id: 'user1',
  name: 'Aisha Khan',
  email: 'aisha@example.com',
  roles: ['STUDENT'],
  avatarUrl: 'https://i.pravatar.cc/150?img=47',
  isActive: true,
  createdAt: '2024-11-01T10:00:00Z',
}

export const mockInstructorUser: User = {
  id: 'user-inst1',
  name: 'Priya Sharma',
  email: 'priya@example.com',
  roles: ['INSTRUCTOR'],
  avatarUrl: 'https://i.pravatar.cc/150?img=45',
  isActive: true,
  createdAt: '2024-09-15T10:00:00Z',
}

export const mockAdminUser: User = {
  id: 'user-admin1',
  name: 'Admin User',
  email: 'admin@kala.app',
  roles: ['ADMIN'],
  isActive: true,
  createdAt: '2024-01-01T10:00:00Z',
}

export const mockInstructors: InstructorProfile[] = [
  {
    id: 'inst1',
    userId: 'user-inst1',
    user: { id: 'user-inst1', name: 'Priya Sharma', email: 'priya@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=45', isActive: true, createdAt: '2024-09-15T10:00:00Z' },
    bio: 'Certified mehendi artist with 10 years of experience in bridal, Arabic, and mandala designs. I teach from basics to advanced bridal patterns.',
    pricing: 799,
    skillPricing: { s2: 799, s1: 649 },
    instagramUrl: 'https://instagram.com/priya.mehendi',
    location: 'Mumbai, Maharashtra',
    isApproved: true,
    avgRating: 4.9,
    isTopRated: true,
    skills: [mockSkills[1], mockSkills[0]],
    portfolioItems: [
      { id: 'p1', instructorId: 'inst1', skillId: 's2', type: 'photo', imageUrl: 'https://picsum.photos/seed/mehendi1/400/300', caption: 'Bridal mehendi full hand' },
      { id: 'p2', instructorId: 'inst1', skillId: 's2', type: 'photo', imageUrl: 'https://picsum.photos/seed/mehendi2/400/300', caption: 'Arabic patterns' },
      { id: 'p3', instructorId: 'inst1', skillId: 's2', type: 'photo', imageUrl: 'https://picsum.photos/seed/mehendi3/400/300', caption: 'Mandala design' },
      { id: 'pv1', instructorId: 'inst1', skillId: 's2', type: 'video', imageUrl: 'https://picsum.photos/seed/mehendi4/400/300', caption: 'Bridal mehendi tutorial' },
      { id: 'p3b', instructorId: 'inst1', skillId: 's1', type: 'photo', imageUrl: 'https://picsum.photos/seed/paint3b/400/300', caption: 'Acrylic flower painting' },
      { id: 'pv2', instructorId: 'inst1', skillId: 's1', type: 'video', imageUrl: 'https://picsum.photos/seed/paint4b/400/300', caption: 'Watercolor blending demo' },
    ],
    createdAt: '2024-09-15T10:00:00Z',
  },
  {
    id: 'inst2',
    userId: 'user-inst2',
    user: { id: 'user-inst2', name: 'Rahul Verma', email: 'rahul@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=12', isActive: true, createdAt: '2024-10-01T10:00:00Z' },
    bio: 'Professional watercolor and acrylic artist teaching expressive painting since 2018. From basic strokes to full landscape paintings.',
    pricing: 999,
    skillPricing: { s1: 999, s4: 1199 },
    instagramUrl: 'https://instagram.com/rahul.paints',
    location: 'Jaipur, Rajasthan',
    isApproved: true,
    avgRating: 4.7,
    isTopRated: true,
    skills: [mockSkills[0], mockSkills[3]],
    portfolioItems: [
      { id: 'p4', instructorId: 'inst2', skillId: 's1', type: 'photo', imageUrl: 'https://picsum.photos/seed/paint1/400/300', caption: 'Watercolor landscape' },
      { id: 'p5', instructorId: 'inst2', skillId: 's1', type: 'photo', imageUrl: 'https://picsum.photos/seed/paint2/400/300', caption: 'Acrylic abstract' },
      { id: 'pv3', instructorId: 'inst2', skillId: 's1', type: 'video', imageUrl: 'https://picsum.photos/seed/paintvid1/400/300', caption: 'Wet-on-wet technique demo' },
      { id: 'p5b', instructorId: 'inst2', skillId: 's4', type: 'photo', imageUrl: 'https://picsum.photos/seed/resin3/400/300', caption: 'Resin geode panel' },
    ],
    createdAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'inst3',
    userId: 'user-inst3',
    user: { id: 'user-inst3', name: 'Sneha Iyer', email: 'sneha@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=32', isActive: true, createdAt: '2024-10-15T10:00:00Z' },
    bio: 'Calligraphy enthusiast teaching Devanagari, Western, and modern lettering. Perfect for beginners wanting to beautify their handwriting.',
    pricing: 599,
    skillPricing: { s3: 599 },
    instagramUrl: 'https://instagram.com/sneha.calligraphy',
    location: 'Bangalore, Karnataka',
    isApproved: true,
    avgRating: 4.8,
    isTopRated: true,
    skills: [mockSkills[2]],
    portfolioItems: [
      { id: 'p6', instructorId: 'inst3', skillId: 's3', type: 'photo', imageUrl: 'https://picsum.photos/seed/calli1/400/300', caption: 'Devanagari calligraphy' },
      { id: 'p7', instructorId: 'inst3', skillId: 's3', type: 'photo', imageUrl: 'https://picsum.photos/seed/calli2/400/300', caption: 'Western script' },
      { id: 'pv4', instructorId: 'inst3', skillId: 's3', type: 'video', imageUrl: 'https://picsum.photos/seed/callivid/400/300', caption: 'Brush pen lettering walkthrough' },
    ],
    createdAt: '2024-10-15T10:00:00Z',
  },
  {
    id: 'inst4',
    userId: 'user-inst4',
    user: { id: 'user-inst4', name: 'Ananya Patel', email: 'ananya@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=56', isActive: true, createdAt: '2024-11-01T10:00:00Z' },
    bio: 'Resin art creator specialising in ocean art, geodes, and functional decor pieces. Learn to pour and create stunning resin masterpieces.',
    pricing: 1299,
    skillPricing: { s4: 1299 },
    instagramUrl: 'https://instagram.com/ananya.resin',
    location: 'Ahmedabad, Gujarat',
    isApproved: true,
    avgRating: 4.6,
    isTopRated: false,
    skills: [mockSkills[3]],
    portfolioItems: [
      { id: 'p8', instructorId: 'inst4', skillId: 's4', type: 'photo', imageUrl: 'https://picsum.photos/seed/resin1/400/300', caption: 'Ocean resin tray' },
      { id: 'p9', instructorId: 'inst4', skillId: 's4', type: 'photo', imageUrl: 'https://picsum.photos/seed/resin2/400/300', caption: 'Geode coasters' },
    ],
    createdAt: '2024-11-01T10:00:00Z',
  },
  {
    id: 'inst5',
    userId: 'user-inst5',
    user: { id: 'user-inst5', name: 'Kavya Nair', email: 'kavya@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=29', isActive: true, createdAt: '2024-11-15T10:00:00Z' },
    bio: 'Clay modelling artist working with polymer and air-dry clay. I teach jewellery making, miniature figurines, and home decor.',
    pricing: 699,
    skillPricing: { s5: 699 },
    instagramUrl: 'https://instagram.com/kavya.clay',
    location: 'Kochi, Kerala',
    isApproved: true,
    avgRating: 4.5,
    isTopRated: false,
    skills: [mockSkills[4]],
    portfolioItems: [
      { id: 'p10', instructorId: 'inst5', skillId: 's5', type: 'photo', imageUrl: 'https://picsum.photos/seed/clay1/400/300', caption: 'Polymer clay earrings' },
      { id: 'p11', instructorId: 'inst5', skillId: 's5', type: 'photo', imageUrl: 'https://picsum.photos/seed/clay2/400/300', caption: 'Miniature food art' },
    ],
    createdAt: '2024-11-15T10:00:00Z',
  },
  {
    id: 'inst6',
    userId: 'user-inst6',
    user: { id: 'user-inst6', name: 'Meera Desai', email: 'meera@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=38', isActive: true, createdAt: '2024-12-01T10:00:00Z' },
    bio: 'Handmade crafts instructor specialising in macrame, weaving, and fabric art. Perfect for those who love slow, mindful crafting.',
    pricing: 499,
    skillPricing: { s6: 499 },
    instagramUrl: 'https://instagram.com/meera.crafts',
    location: 'Pune, Maharashtra',
    isApproved: false,
    avgRating: 4.2,
    isTopRated: false,
    skills: [mockSkills[5]],
    portfolioItems: [
      { id: 'p12', instructorId: 'inst6', skillId: 's6', type: 'photo', imageUrl: 'https://picsum.photos/seed/craft1/400/300', caption: 'Macrame wall hanging' },
    ],
    createdAt: '2024-12-01T10:00:00Z',
  },
]

export const mockSlots: Slot[] = [
  { id: 'slot1', instructorId: 'inst1', skillId: 's2', title: 'Morning Mehendi Session', startTime: '2026-03-10T09:00:00+05:30', endTime: '2026-03-10T10:00:00+05:30', timezone: 'Asia/Kolkata', status: 'AVAILABLE' },
  { id: 'slot2', instructorId: 'inst1', skillId: 's2', title: 'Evening Practice', startTime: '2026-03-12T17:00:00+05:30', endTime: '2026-03-12T18:30:00+05:30', timezone: 'Asia/Kolkata', status: 'AVAILABLE' },
  { id: 'slot1b', instructorId: 'inst1', skillId: 's1', title: 'Painting Workshop', startTime: '2026-03-11T11:00:00+05:30', endTime: '2026-03-11T12:00:00+05:30', timezone: 'Asia/Kolkata', status: 'AVAILABLE' },
  { id: 'slot3', instructorId: 'inst2', skillId: 's1', title: 'Watercolor Basics', startTime: '2026-03-11T10:00:00+05:30', endTime: '2026-03-11T11:30:00+05:30', timezone: 'Asia/Kolkata', status: 'BOOKED' },
  { id: 'slot4', instructorId: 'inst2', skillId: 's1', title: 'Advanced Painting', startTime: '2026-03-15T14:00:00+05:30', endTime: '2026-03-15T15:30:00+05:30', timezone: 'Asia/Kolkata', status: 'AVAILABLE' },
  { id: 'slot5', instructorId: 'inst3', skillId: 's3', title: 'Calligraphy for Beginners', startTime: '2026-03-13T11:00:00+05:30', endTime: '2026-03-13T12:00:00+05:30', timezone: 'Asia/Kolkata', status: 'AVAILABLE' },
  { id: 'slot6', instructorId: 'inst4', skillId: 's4', title: 'Resin Ocean Art', startTime: '2026-03-14T15:00:00+05:30', endTime: '2026-03-14T17:00:00+05:30', timezone: 'Asia/Kolkata', status: 'AVAILABLE' },
]

export const mockBookings: Booking[] = [
  {
    id: 'book1',
    studentId: 'user1',
    studentName: 'Aisha Khan',
    instructorId: 'inst1',
    instructor: mockInstructors[0],
    slotId: 'slot1',
    slot: mockSlots[0],
    status: 'CONFIRMED',
    payment: { id: 'pay1', bookingId: 'book1', amount: 799, status: 'SUCCESS', provider: 'RAZORPAY', transactionId: 'pay_QtY8X123' },
    messages: [
      { id: 'msg1', bookingId: 'book1', senderId: 'user1', senderName: 'Aisha Khan', content: 'Hi! Looking forward to the session.', createdAt: '2026-03-08T10:00:00Z' },
      { id: 'msg2', bookingId: 'book1', senderId: 'user-inst1', senderName: 'Priya Sharma', content: 'Welcome! Please keep your henna cone ready.', createdAt: '2026-03-08T11:00:00Z' },
    ],
    createdAt: '2026-03-08T09:00:00Z',
  },
  {
    id: 'book2',
    studentId: 'user1',
    studentName: 'Aisha Khan',
    instructorId: 'inst2',
    instructor: mockInstructors[1],
    slotId: 'slot3',
    slot: mockSlots[2],
    status: 'COMPLETED',
    payment: { id: 'pay2', bookingId: 'book2', amount: 999, status: 'SUCCESS', provider: 'STRIPE', transactionId: 'pi_3NZ123' },
    review: { id: 'rev1', bookingId: 'book2', studentId: 'user1', studentName: 'Aisha Khan', instructorId: 'inst2', rating: 5, comment: 'Wonderful session! Rahul is an amazing teacher.', createdAt: '2026-03-12T15:00:00Z' },
    messages: [],
    createdAt: '2026-03-09T09:00:00Z',
  },
  {
    id: 'book3',
    studentId: 'user1',
    studentName: 'Aisha Khan',
    instructorId: 'inst3',
    instructor: mockInstructors[2],
    slotId: 'slot5',
    slot: mockSlots[4],
    status: 'CANCELLED',
    payment: { id: 'pay3', bookingId: 'book3', amount: 599, status: 'REFUNDED', provider: 'RAZORPAY', transactionId: 'rfnd_K3X7Z99' },
    messages: [],
    createdAt: '2026-03-07T09:00:00Z',
  },
  {
    id: 'book4',
    studentId: 'user1',
    studentName: 'Aisha Khan',
    instructorId: 'inst4',
    instructor: mockInstructors[3],
    slotId: 'slot6',
    slot: mockSlots[5],
    status: 'INITIATED',
    messages: [],
    createdAt: '2026-03-01T09:00:00Z',
  },
]

export const mockReviews: Review[] = [
  { id: 'rev1', bookingId: 'book2', studentId: 'user1', studentName: 'Aisha Khan', instructorId: 'inst2', rating: 5, comment: 'Wonderful session! Rahul is an amazing teacher. Learned so much about watercolor in just one hour.', createdAt: '2026-03-12T15:00:00Z' },
  { id: 'rev2', bookingId: 'book5', studentId: 'user2', studentName: 'Riya Singh', instructorId: 'inst1', rating: 5, comment: 'Priya is incredibly talented. My bridal mehendi turned out perfect!', createdAt: '2026-02-20T15:00:00Z' },
  { id: 'rev3', bookingId: 'book6', studentId: 'user3', studentName: 'Pooja Mehta', instructorId: 'inst3', rating: 4, comment: 'Great calligraphy class, very patient instructor.', createdAt: '2026-02-18T15:00:00Z' },
  { id: 'rev4', bookingId: 'book7', studentId: 'user4', studentName: 'Kiran Joshi', instructorId: 'inst1', rating: 5, comment: 'Absolutely loved the mandala session. Highly recommend!', createdAt: '2026-02-15T15:00:00Z' },
]

export const mockAdminStats: AdminStats = {
  totalUsers: 1240,
  totalInstructors: 87,
  totalBookings: 3456,
  revenue: 1245000,
}

export const pendingInstructors: InstructorProfile[] = [
  mockInstructors[5],
  {
    id: 'inst7',
    userId: 'user-inst7',
    user: { id: 'user-inst7', name: 'Rohan Kapoor', email: 'rohan@example.com', roles: ['INSTRUCTOR'], avatarUrl: 'https://i.pravatar.cc/150?img=15', isActive: true, createdAt: '2025-01-05T10:00:00Z' },
    bio: 'Warli and folk art specialist wanting to preserve and share traditional Indian art forms.',
    pricing: 649,
    location: 'Nashik, Maharashtra',
    isApproved: false,
    avgRating: 0,
    isTopRated: false,
    skills: [mockSkills[0]],
    portfolioItems: [
      { id: 'p13', instructorId: 'inst7', skillId: 's1', type: 'photo', imageUrl: 'https://picsum.photos/seed/warli1/400/300', caption: 'Warli painting' },
    ],
    createdAt: '2025-01-05T10:00:00Z',
  },
]
